### ISSUE TITLE
Project status is not updated once being re-opened

### ISSUE THREAD

**Issue by muzaimahnor** [samheather/iapt2group1#16]
When a project owner rejects all transcriptions and re-opens the project to public, the project status remains as "Image Closed for Transcriptions"

**Comment by samheather** [comment]
@svetlanaangelova self-assigned - are you working on this one or should I take it?

**Comment by svetlanaangelova** [comment]
@samheather I'm still not sure what needs to be done for this, so go for it.

**Comment by samheather** [comment]
Neither am I. I thought I was arguing that we already handled it fine, and
you wanted to add some special thing on for rejecting all?

On Friday, 3 April 2015, svetlanaangelova notifications@github.com wrote:

> @samheather https://github.com/samheather I'm still not sure what needs
> to be done for this, so go for it.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/samheather/iapt2group1/issues/16#issuecomment-89205882
> .

## 

_Sam Heather_ | pingWHEN | m: +44 7585 441757 <00447585441757> | e:
sam@heather.sh

Website: www.pingwhenapp.com
Facebook: www.facebook.com/pingwhen
https://www.facebook.com/pages/Pingwhen/292317570939511
*a personal safety app for when you arrive (or don't) to a location. *

**Comment by samheather** [comment]
Decision: Change button title to say "Reject all and re-open image"
Add info box to top area saying "Image temporaiirly closed as has got 3 pending transcriptions. Either accept them, or reject them to re-open this individual image for transcription.

**Comment by samheather** [comment]
Done at last. Bearing in mind the amount of discussion in this, you might want to check this is what we both envisioned @svetlanaangelova

**Comment by svetlanaangelova** [comment]
Looks good to me, @samheather
