### ISSUE TITLE
make new collection visible to logged out users as well

### ISSUE THREAD

**Issue by samheather** [samheather/iapt2group1#33]

**Comment by samheather** [comment]
This breaks the title bar into two lines with some screen sizes:
![screen shot 2015-04-03 at 17 30 27](https://cloud.githubusercontent.com/assets/3355771/6985081/372b33c8-da27-11e4-902d-85f8f02d6790.png)

**Comment by samheather** [comment]
@svetlanaangelova and @svetlanaangelova to discuss in call

**Comment by svetlanaangelova** [comment]
I'll talk to myself, it's fine.

**Comment by samheather** [comment]
whoops - both our GH usernames start with the same so assuming auto-complete will save me is a bad assumption.
@svetlanaangelova, we talked about this, and you've removed some of the stuff from the title bar. But the long brand, long search bar and "Create" word in "Create New Project" together still make this title bar too long and it still goes on to two lines.
Any thoughts?

**Comment by svetlanaangelova** [comment]
Renaming Collection to Project and moving the Login/Logout/Register links didn't help?

**Comment by samheather** [comment]
Yeah it helped, but not enough. Try it on yours - drag your window and gradually make it smaller.

**Comment by samheather** [comment]
Finally fixed in e7ea4b63565e1fd9f4edd546fbddcb3f96d3b237
