### ISSUE TITLE
AddField page form: replace the label for the form field 'Label' with 'What do you want transcribing into this field?'

### ISSUE THREAD

**Issue by samheather** [samheather/iapt2group1#41]
AddField page form: replace the label for the form field 'Label' with 'What do you want transcribing into this field?'

**Comment by svetlanaangelova** [comment]
Isn't that a mouthful?

**Comment by samheather** [comment]
Yes but at least it actually tells the person what to put into that box.
And it's helpful text. Label is just super ambiguous.

On Friday, 3 April 2015, svetlanaangelova notifications@github.com wrote:

> Isn't that a mouthful?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/samheather/iapt2group1/issues/41#issuecomment-89206018
> .

## 

_Sam Heather_ | pingWHEN | m: +44 7585 441757 <00447585441757> | e:
sam@heather.sh

Website: www.pingwhenapp.com
Facebook: www.facebook.com/pingwhen
https://www.facebook.com/pages/Pingwhen/292317570939511
*a personal safety app for when you arrive (or don't) to a location. *

**Comment by svetlanaangelova** [comment]
Then I would prefer to see a comment explaining what it should be rather
than put everything in the label. I don't know what the others think.

**Comment by j6mes** [comment]
How about placeholder text?

**Comment by samheather** [comment]
Yep placeholder would be fine, I'll deal with it.

On Friday, 3 April 2015, j6mes notifications@github.com wrote:

> How about placeholder text?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/samheather/iapt2group1/issues/41#issuecomment-89248966
> .

## 

_Sam Heather_ | pingWHEN | m: +44 7585 441757 <00447585441757> | e:
sam@heather.sh

Website: www.pingwhenapp.com
Facebook: www.facebook.com/pingwhen
https://www.facebook.com/pages/Pingwhen/292317570939511
*a personal safety app for when you arrive (or don't) to a location. *

**Comment by samheather** [comment]
going in as a comment
