### ISSUE TITLE
Remove confirmations screens from non destructive actions like OPEN

### ISSUE THREAD

**Issue by samheather** [samheather/iapt2group1#55]

**Comment by svetlanaangelova** [comment]
Will there be no confirmation at all?

**Comment by svetlanaangelova** [comment]
@samheather , thoughts?

**Comment by samheather** [comment]
Sorry - I don't know. It feels bad to get rid of them, but then Chris does say they're bad. I'd argue that accepting or rejecting a transx is more destructive them opening / closing, since these can not be undone. 
Checkout these slides: https://docs.google.com/a/york.ac.uk/viewer?a=v&pid=sites&srcid=eW9yay5hYy51a3xpYXB0fGd4OjJiYzMwMjE5Yjg3NzIxOWU
(Lecutre 6, AUTUMN term).
where Chris expresses this hate. He showed in the lecture a bar that came up from the bottom (like the Gmail sent bar) saying 'You have deleted this. But you can click here to recover it', so it was a passive, non-interupting confirmation with cancel option.

I have this on Gmail for undoing sending an email - it's passive so I don't have to click an 'are you sure' every time, but for 10 seconds I have an option to undo. I think implementing this would be a waste of time, but perhaps we could describe it in the report as a possibility we considered which we would have liked to have done given more time?

3 screnshots below show it before the Undo disappears, after, and in context.

![screen shot 2015-04-06 at 15 15 49](https://cloud.githubusercontent.com/assets/3355771/7005506/4892809e-dc70-11e4-8287-89f76f7d91dc.png)

![screen shot 2015-04-06 at 15 15 58](https://cloud.githubusercontent.com/assets/3355771/7005511/5422ef48-dc70-11e4-9257-491d06b3b985.png)

![screen shot 2015-04-06 at 15 15 46](https://cloud.githubusercontent.com/assets/3355771/7005513/588ec3a4-dc70-11e4-9d15-cd7b888e39d1.png)

**Comment by svetlanaangelova** [comment]
However, Sam, I'd argue that this bar which appears for 10 or however many
seconds is bad for accessibility. See here - http://www.w3.org/TR/WCAG20/#time-limits-required-behaviors for what I mean.

**Comment by samheather** [comment]
Hmm...I didn't think of that. The bar is good for usability, but not accessibility. Forget the time limit, make the bar be there until they go to the next page - then it is accessible and usable.
But...it's still hard to implement, and do screen readers pick up changes to the DOM like bars been addd (I guess this would be JavaScript?)?

I'm afk for a few hours, but should be back tonight by 7 bst to continue discussing, maybe on hangouts?

**Comment by svetlanaangelova** [comment]
re: screenreaders and changes to DOM - I'd bet it's different from screenreader to screenreader.

re: later - dealio.

**Comment by samheather** [comment]
@j6mes "we'd really appreciate your assistance in this matter" ~Sve 
We can't decide what to do with confirmations and alerts. We're aware it could be a couple of marks if we get it wrong - assuming that destructive, irreversible actions don't need confirmations seems high risk and wrong (bearing in mind that as Sve says, very often users of critical systems have a mental age of 14), but doing so means putting intermediary confirmation screens in (like alerts) that interrupt the users flow in the app. We're worried about doing this as well though, as we would have to do all or nothing (i.e. add confirmation screens in for opening/closing a project, and accepting or rejecting a transcription (we did consider adding a simple undo button for accepting or rejecting tx's, but that's more complicated then it seems at first thought). Having to click through a alert screen for every accept/reject of a TX doesn't seem very usable.

Can we have your input on this please?
