### ISSUE TITLE
Sam to check:

### ISSUE THREAD

**Issue by samheather** [samheather/iapt2group1#67]
Should closed projects still be visible to the general public, according to Chris Spec & ans?

**Comment by svetlanaangelova** [comment]
Hope this helps (from the spec): "When open, all users of your crowdsourcing site should be able to find the project and provide the desired transcriptions for document images of their choosing within the project."

I read this when open, make it available to the public. When closed, do the opposite.

And we've accommodated for that via the database views.

**Comment by samheather** [comment]
I've re-read the brief and am inclined to agree. _however_, I'm wondering what the purpose of accepting a transcription is. I wonder if we're meant to be making accepted transcriptions visible to the public (hence it's a crowd sourced site where a shared knowledge base is built up). I don't think the brief says this, and having reviewed the assessment questions I don't see anything to suggest he is expecting submitted transcriptions to be public. But it's a critical part, so it'd be good if another pair of eyes double-checked this please? 
https://sites.google.com/a/york.ac.uk/iapt/assessments
(Close this if you do and agree)
