### ISSUE TITLE
Skip to main content link doesnt work in firefox mac 37.0.1

### ISSUE THREAD

**Issue by j6mes** [samheather/iapt2group1#83]

**Comment by samheather** [comment]
Same here - and Chris tests using Firefox I think.

**Comment by j6mes** [comment]
Nor does it affect te tab order. If you use the link it only moves the page, but if you tab up, the next item in the menu is still used

**Comment by svetlanaangelova** [comment]
Interesting. I read that IE and Chrome might have an issue with it but nothing about Macs. Do you get any errors on the console?

**Comment by j6mes** [comment]
no. but it works on chrome 
https://www.dropbox.com/s/uffyaj4w4dkpsr5/Screenshot%202015-04-15%2014.28.36.png?dl=0

**Comment by samheather** [comment]
@svetlanaangelova also seeing the same - that it works on Chrome but not firefox

**Comment by svetlanaangelova** [comment]
Could it be due to a bug in the latest firefox?
