### ISSUE TITLE
Show required fields as required on submission forms.

### ISSUE THREAD

**Issue by svetlanaangelova** [samheather/iapt2group1#89]

**Comment by samheather** [comment]
wow good point - how did we miss this one?!

On 15 April 2015 at 14:01, svetlanaangelova notifications@github.com
wrote:

> —
> Reply to this email directly or view it on GitHub
> https://github.com/samheather/iapt2group1/issues/89.

## 

_Sam Heather_ | pingWHEN | m: +44 7585 441757 <00447585441757> | e:
sam@heather.sh

Website: www.pingwhenapp.com
Facebook: www.facebook.com/pingwhen
https://www.facebook.com/pages/Pingwhen/292317570939511
*a personal safety app for when you arrive (or don't) to a location. *
